[[redirects]]
    from = "/*"
    to = "https://jugem.netlify.app/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/html/*"
    to = "https://jugem.netlify.app"
    status = 301
    force = true